### PR TITLE
css reset for recaptcha to fix display issues

### PR DESCRIPTION
**Pull request by bitboxer**

### CODE REVIEW

**Comment by bascht** [comment]
Well. If it renders alright on Linux, then everything is fine. :)

screenshot from 2015-01-03 02 21 18

**Comment by moonglum** [comment]
Amazing!

**Comment by bitboxer** [comment]
Not amazing, it's a missing reset on Recaptcha. I hate the "let's embed html and reset everything that might have changed" approach. I hope the component stuff will be usable soonish.

**Comment by moonglum** [comment]
Amazing that you fixed it, not that you had to do it :wink:

**Pull request merged**
