### PR TITLE
Add sync script for production → master

### PR DESCRIPTION
**Pull request by bascht**
Fairly simple:

* Shut down master
* Dump production db
* Delete + recreate master
* Sync uploads
* Restart master

(refs #621)

### CODE REVIEW

**Comment by moonglum** [comment]
This script has a problem: What if one of the system calls fail?

```ruby
require 'logger'

logger = Logger.new(STDOUT)

logger.info 'hi'
system 'haahaha'
logger.info 'bye'
```

Result:

```
I, [2016-03-26T19:25:12.440048 #1917]  INFO -- : hi
I, [2016-03-26T19:25:12.440725 #1917]  INFO -- : bye
```

Nothing indicates that the command haahaha does not exist. It is not in the log, it is not in the status code. I think that could lead to some pretty bad situations where problems in that script would never be known. Compare it to this script:

```ruby
require 'logger'

logger = Logger.new(STDOUT)

logger.info 'hi'
system 'haahaha' or logger.error('haahaha does not exist') and exit(1)
logger.info 'bye'
```

Result:

```
I, [2016-03-26T19:22:14.105625 #1726]  INFO -- : hi
E, [2016-03-26T19:22:14.106079 #1726] ERROR -- : haahaha does not exist
```

**Comment by moonglum** [comment]
The rest of the script looks really solid :+1: Great work!!!

**Comment by bascht** [comment]
Re-Test. :smi

**Comment by moonglum** [comment]
Great :blue_heart:

**Pull request merged**
