### PR TITLE
Adding a sleep to throttle the api requests, hopefully fixes #567

### LINKED ISSUE #567: Radar does not work for mrgn-in
Somehow the radar system does not work for the mrgn.in usergroup. Don't know what is wrong there, have to check

### PR DESCRIPTION
**Pull request by bitboxer**
This is just a first try to fix the api throtteling. If this is not working, we need to find a smarter way to do this.

### CODE REVIEW

**Comment by bitboxer** [comment]
@moonglum can you review this? Need this on production asap :wink:

**Comment by bascht** [comment]
This change lies in the range of what think I'm capable of reviewing in a rails app. :)

**Comment by moonglum** [comment]
Yep, I think that's the best way to do it for now. Other solutions would be worker queues with retries etc. – but I think that would be a little bit overengineered for this task.

**Comment by bascht** [comment]
:+1:

**Comment by bitboxer** [comment]
Let's see if this works. Somewhere in the last few months meetup must have increased the throtteling. The next step would be to use the http headers they sent us to analyze the throtteling and wait X minutes before the next request.

**Pull request merged**
