### PR TITLE
Upgrade to latest Puppet module

### PR DESCRIPTION
**Pull request by bascht**
* All the goodness, all the speed, no bugs ®

### CODE REVIEW

**Comment by bascht** [comment]
Great. Looks like I broke the build already. @bitboxer @moonglum `.ruby-version` needs to specify a *full* version number?

**Comment by bascht** [comment]
Note to self: 
* RVM is okay with a major / minor number.
* We have been testing with the wrong Ruby version in Travis for the last months.

**Comment by moonglum** [comment]
This is not working :cry: See my [comment here](https://github.com/hacken-in/puppet-hackenin/commit/44e3f86f9445f147d1e54be35ac80edb6ddb7caf).

**Comment by moonglum** [comment]
It works, it works!

**Comment by moonglum** [comment]
Thanks, @bascht

**Pull request merged**
