### PR TITLE
Back to uberspace (refs #607)

### PR DESCRIPTION
**Pull request by bascht**

### CODE REVIEW

**Comment by moonglum** [comment]
That was a lot of hacking :laughing: IMHO the current status is:

* [x] Some Bug Fixes, implemented pending tests and cleanup (#612, #594)
* [x] Gem Updates, especially ActiveAdmin (from Git to the prerelease of 1.0.0) and Rails (to 4.2.5.1)
* [x] Make CodeClimate Reporting work and remove SimpleCov #586
* [x] Removed the unused style guide and the according gems
* [x] Region organizers are allowed to upload pictures, closes #612
* [x] Deploy from Travis, removing the need for Codeship
* [x] Make everything run on Uberspace, now staging (https://master.hacken.in) is on CodeShip, deployed by Travis with HTTPS via Let's Encrypt
* [x] Remove memcached and dalli, as we don't use caching anyway
* [ ] Setup Postgres Backup
* [ ] Remove the Codeship Build
* [ ] Make the Github Login work
* [ ] Adjust [The Pamphlet](https://github.com/hacken-in/website/blob/master/CONTRIBUTING.md#contributing-code-aka-the-pamphlet) :tm: 
* [ ] Adjust the [humans page](https://github.com/hacken-in/website/blob/master/CONTRIBUTING.md#contributing-code-aka-the-pamphlet)

@bascht Is that right? Am I missing something? I'll look into the remaining todos during this week. Then I'll click through all the stuff on master.hacken.in, checking if everything works. Clean up the commits and merge. Then we can pull over production, too. @bitboxer asked us to give him a 24 hour notice for that.

**Comment by bascht** [comment]
@moonglum I'll have to sync that list with the one in #607 but yeah. Looks complete. :)

**Comment by moonglum** [comment]
Will our recurring jobs still work? I see a "Migrate Shellycloud (Whenever) schedule.rb" task :smile: 

How do we handle the staging database currently? Do we have something that pulls over the production database into staging?

**Comment by bascht** [comment]
Jobs: Not out of the box (therefore the to do entry)
Staging: That would be easier with cronjobs on uberspace. :)

**Comment by moonglum** [comment]
Jobs: Added above!
Staging: Yep, that's what I was thinking :smile: Added above!

**Pull request merged**
