### PR TITLE
Hacken.in/Hamburg

### PR DESCRIPTION
**Pull request by moonglum**
Hacken.in Hamburg is now ready! We can add it to the homepage!

### CODE REVIEW

**Comment by moonglum** [comment]
@bascht Review, please? :smile:

**Comment by bascht** [comment]
Middle of the Außenalster looks like the proper centre of Hamburg! :)

**Comment by bascht** [comment]
Looks good! It could use a little padding on the northern bit though. :)

**Comment by moonglum** [comment]
@bascht Good point! Forgot to add them to the list bounds thingy: #627

**Pull request merged**
