### PR TITLE
Added missing translation for event participation, closes #554

### LINKED ISSUE #554: Notify has no translation and does not close when pressing (x)
I pressed "i attend" on this event and saw this notification:

photo

It

* misses the translation
* does not close when pressing (x)

### PR DESCRIPTION
**Pull request by bitboxer**

### CODE REVIEW

**Comment by bitboxer** [comment]
This is strange. My local rake task does not find any missing translations. But the one on the ci does. Can someone help me to investigate this?

**Comment by thegcat** [comment]
Lokal kriege ich den gleichen Fehler, und:

```
% i18n-tasks missing                                                                                                                                                        !10014
Missing translations (4) | i18n-tasks v0.7.10
+--------+-----------------------------------+----------------------------+
| Locale | Key                               | Details                    |
+--------+-----------------------------------+----------------------------+
|   de   | subscriptions.delete.confirmation | You no longer participate. |
|   de   | subscriptions.push.confirmation   | You now participate.       |
|   en   | single_events.delete.confirmation | Du nimmst nicht mehr teil. |
|   en   | single_events.push.confirmation   | Du nimmst jetzt teil.      |
+--------+-----------------------------------+----------------------------+
```

Weiter habe ich da nicht reingeschaut, hilft dir das?

**Comment by bitboxer** [comment]
Das sollte eigentlich von 4d6d626 repariert werden :disappointed: .

**Comment by thegcat** [comment]
Was du committest wollte ich gerade schreiben.

Anmerkung: Ich wäre dafür explizit `{delete,push}` statt einmal alles `*` zu nutzen.

**Comment by bitboxer** [comment]
Okay, Found the problem. Pebcab

**Comment by thegcat** [comment]
What. The keys seem to be unused and missing at the same time on my setup *sigh*

**Comment by thegcat** [comment]
Soooo, I don't know why glebm/i18n-tasks seems to recognizes those 4 keys as missing and unused, but well, it works like this.

I'd like to rebase this, objections?

**Comment by bitboxer** [comment]
Nope, go ahead.

**Comment by thegcat** [comment]
I opened glebm/i18n-tasks#127 to ask for help on this, I don't want to block on this though and would rather have a strange i18n-tasks config instead of missing the keys.

**Comment by thegcat** [comment]
This is rebased and can be reviewed and if applicable merged once the CIs are through.

**Pull request merged**
